/**
 * GitHub Reporter - PR comment format
 */

export function formatPRComment(violations, options = {}) {
  const { repo = '', sha = '', showSuggestions = true } = options;

  if (violations.length === 0) {
    return `## ✅ Design System Check Passed\n\nNo design system violations found. Great job! 🎉`;
  }

  const lines = [];
  const errors = violations.filter(v => v.severity === 'error');
  const warnings = violations.filter(v => v.severity === 'warn');

  // Header with badge
  lines.push(`## ❌ ${violations.length} Design System Violation${violations.length > 1 ? 's' : ''}`);
  lines.push('');

  // Summary badges
  if (errors.length > 0) lines.push(`🔴 **${errors.length} error${errors.length > 1 ? 's' : ''}**`);
  if (warnings.length > 0) lines.push(`🟡 **${warnings.length} warning${warnings.length > 1 ? 's' : ''}**`);
  lines.push('');

  // Violations table
  lines.push('| File | Line | Severity | Issue |');
  lines.push('|------|------|----------|-------|');

  for (const v of violations.slice(0, 25)) {
    const severity = v.severity === 'error' ? '🔴 Error' : '🟡 Warning';
    const file = v.file ? v.file.replace(/^.*[\\/]/, '') : 'unknown';
    const link = repo && sha ? `[${file}](/${repo}/blob/${sha}/${v.file}#L${v.line})` : file;

    lines.push(`| ${link} | ${v.line} | ${severity} | ${v.message} |`);
  }

  if (violations.length > 25) {
    lines.push('');
    lines.push(`_...and ${violations.length - 25} more violations_`);
  }

  // Suggestions section
  if (showSuggestions) {
    const withSuggestions = violations.filter(v => v.suggestion).slice(0, 5);
    if (withSuggestions.length > 0) {
      lines.push('');
      lines.push('### 💡 Suggested Fixes');
      lines.push('');

      for (const v of withSuggestions) {
        lines.push(`- **${v.file}:${v.line}**: ${v.suggestion}`);
      }
    }
  }

  // Footer
  lines.push('');
  lines.push('---');
  lines.push('_Generated by [DesignLint](https://github.com/click-ship/design-lint)_');

  return lines.join('\n');
}

export function formatAnnotations(violations) {
  return violations.map(v => ({
    path: v.file,
    start_line: v.line,
    end_line: v.line,
    annotation_level: v.severity === 'error' ? 'failure' : 'warning',
    message: v.message,
    title: `Design System: ${v.rule}`,
    raw_details: v.suggestion || undefined
  }));
}

export function formatCheckRun(violations, options = {}) {
  const { name = 'Design Lint', headSha } = options;
  const conclusion = violations.some(v => v.severity === 'error') ? 'failure' : 'success';

  return {
    name,
    head_sha: headSha,
    status: 'completed',
    conclusion,
    output: {
      title: `${violations.length} design system violation${violations.length !== 1 ? 's' : ''} found`,
      summary: formatPRComment(violations, options),
      annotations: formatAnnotations(violations).slice(0, 50)
    }
  };
}

export default { formatPRComment, formatAnnotations, formatCheckRun };

/**
 * Drift as a markdown block for a pull request comment.
 *
 * Separate from formatPRComment because drift is not a violation: it is a
 * disagreement between two sources of truth, neither of which is authoritative, and
 * nothing in the diff under review necessarily caused it.
 */
export function formatDriftSection(drift) {
  if (!drift?.available || drift.drifted.length === 0) return '';

  const lines = [];
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`### ${drift.drifted.length} token${drift.drifted.length === 1 ? '' : 's'} drifted from Figma`);
  lines.push('');
  lines.push('| token | code | figma | |');
  lines.push('|---|---|---|---|');

  for (const entry of drift.drifted) {
    const notes = [
      entry.detail,
      entry.usages > 0 ? `${entry.usages} usage${entry.usages === 1 ? '' : 's'}` : 'unused'
    ].filter(Boolean).join(' · ');

    lines.push(`| \`${entry.codeName}\` | \`${entry.codeValue}\` | \`${entry.figmaValue}\` | ${notes} |`);
  }

  lines.push('');
  lines.push('<sub>Neither side is authoritative. Update whichever one is wrong.</sub>');

  return lines.join('\n');
}
